# coding=utf-8
MENU_ALPHA = 90  # Alpha of menu color, 0: Opaque, 255: Transparent
MENU_BGCOLOR = (0, 0, 0)  # Background color of Menu
MENU_CENTERED_TEXT = True  # Menu centered text
MENU_DRAW_X = 50  # Upper-left X-Position of objects into Menu
MENU_DRAW_Y = 60  # Upper-left Y-Position of objects into Menu
MENU_FONT_COLOR = (255, 255, 255)  # Font color
MENU_FONT_SIZE = 40  # Font size of entries
MENU_FONT_SIZE_TITLE = 50  # Menu font size title
MENU_HEIGHT = 400  # Menu height (px)
MENU_OPTION_MARGIN = 15  # Option margin (px)
MENU_OPTION_SHADOW = True  # Indicates if a shadow is drawn on selected option
MENU_SELECTED_DRAW = True  # Indicates if rectangle is drawn on a selected item
MENU_SELECTED_WIDTH = 1  # Width of selected item
MENU_SELECTEDCOLOR = (180, 180, 180)  # Color of selected item
MENU_TITLE_BG_COLOR = (27, 74, 128)#(170, 65, 50)  # Background color
MENU_WIDTH = 600  # Width of Menu (px)
SHADOW_COLOR = (0, 0, 0)  # Shadow color
